-- Migration to alter companies, spaces, and offers tables to support full form fields and soft delete fields

-- 1. Companies additions
ALTER TABLE companies ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tax_no VARCHAR(50);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tax_office VARCHAR(100);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS media_agency VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS creative_agency VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS contacts JSONB DEFAULT '[]'::jsonb;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS brands JSONB DEFAULT '[]'::jsonb;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- 2. Spaces additions
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS terminal VARCHAR(100);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS floor VARCHAR(100);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS price VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS visibility VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS resolution VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS pitch VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS working_hours VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS audio VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS power VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS file_format VARCHAR(100);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS max_file_size VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS update_interval VARCHAR(50);
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);

-- 3. Offers additions
ALTER TABLE offers ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS closing_date VARCHAR(50);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS spaces_list JSONB DEFAULT '[]'::jsonb;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS details TEXT;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
